"""milestone10_add_webhooks

Revision ID: 0715967f76c3
Revises: 3d1b14bb6b38
Create Date: 2026-03-13 14:10:44.229113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0715967f76c3'
down_revision = '3d1b14bb6b38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('endpoint_url', sa.String(length=2048), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('secret_token', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webhooks')
    # ### end Alembic commands ###
