"""milestone11_add_agent_wings_fields

Revision ID: 77f298ea83c4
Revises: 0715967f76c3
Create Date: 2026-03-13 14:46:06.100928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77f298ea83c4'
down_revision = '0715967f76c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheme', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('daemon_connect', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('daemon_listen', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('daemon_token_id', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('daemon_token', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_column('daemon_token')
        batch_op.drop_column('daemon_token_id')
        batch_op.drop_column('daemon_listen')
        batch_op.drop_column('daemon_connect')
        batch_op.drop_column('scheme')

    # ### end Alembic commands ###
